[package]
name = "geev-core"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { version = "22.0.0", default-features = false }

[dev-dependencies]
soroban-sdk = { version = "22.0.0", features = ["testutils"] }
